

# ===============================
# DATABASE CONFIG (Local MySQL)
# ===============================
# ===============================
# DATABASE CONFIG (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d7o7jh8sfn5c73egsecg-a.ohio-postgres.render.com:5432/student_analytics
spring.datasource.username=student_analytics_user
spring.datasource.password=1fpd14atKWM4gMnvQnEcExB1z7PWPrGZ
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ===============================
# SERVER CONFIG (RENDER PORT FIX)
# ===============================
server.port=${PORT:8080}

# ===============================
# OPTIONAL (FOR DEBUGGING)
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always